In [1]:
%load_ext autoreload
%autoreload 2
from benchmark.utils import *
from benchmark.preprocess import *
from benchmark.constants import *
from benchmark.db_import import *
from benchmark.ground_truth import *
from benchmark.construct_threatrace_graph import *
#from benchmark import sql_api
import logging 
logging.basicConfig(
    format='%(asctime)s - %(levelname)s - %(message)s',
    level=logging.INFO,
    filename='app.log',
    #filemode='w'
    filemode='a',
)
logging.info('This will get logged to a file')

In [4]:
import configparser
config_dir = "/Users/robinbuchta/Documents/GitHub/trustathsh/projekte/secder/Fachliches/darpa_benchmark_lite_sql/configs"
config_file_record_03 = config_dir + '/eng3/cadets/cadets_03_record.ini'
config_rec3 = configparser.ConfigParser()
config_rec3.read(config_file_record_03)


['/Users/robinbuchta/Documents/GitHub/trustathsh/projekte/secder/Fachliches/darpa_benchmark_lite_sql/configs/eng3/cadets/cadets_03_record.ini']

In [5]:
create_threatrace_edge_list(config_rec3, False)
create_threatrace_edge_list(config_rec3, True)

rearrange_nodes

                CREATE OR REPLACE TABLE cadets_r03_tt_nodes_train AS
                SELECT DISTINCT src_num AS num, src_uuid AS node, type_s as node_type FROM tmp2_benign
                UNION
                SELECT DISTINCT dst_num AS num, dst_uuid AS node, dst_type as node_type FROM tmp2_benign 
                ORDER BY num;

                ALTER TABLE cadets_r03_tt_nodes_train ADD id INTEGER UNIQUE KEY AUTO_INCREMENT;

                CREATE INDEX IF NOT EXISTS node_id ON cadets_r03_tt_nodes_train (id);
                

                CREATE INDEX IF NOT EXISTS num ON cadets_r03_tt_nodes_train (num);
                
 
                CREATE OR REPLACE TABLE cadets_r03_tt_edges_train AS
                SELECT e.id
                        , src_uuid
                        , src_num
                        , type_s
                        , dst_uuid 
                        , dst_num 
                        , dst_type
                        , event_type
       

In [2]:
import configparser
config_dir = "/Users/robinbuchta/Documents/GitHub/trustathsh/projekte/secder/Fachliches/darpa_benchmark_lite_sql/configs"
config_file_record_01 = config_dir + '/eng3/cadets/cadets_01_record.ini'
config_rec1 = configparser.ConfigParser()
config_rec1.read(config_file_record_01)


['/Users/robinbuchta/Documents/GitHub/trustathsh/projekte/secder/Fachliches/darpa_benchmark_lite_sql/configs/eng3/cadets/cadets_01_record.ini']

In [6]:
def print_data_stats(data):
    print()
    print(data)
    print('===========================================================================================================')

    # Gather some statistics about the graph.
    print(f'Number of nodes: {data.num_nodes}')
    print(f'Number of edges: {data.num_edges}')
    print(f'Average node degree: {data.num_edges / data.num_nodes:.2f}')
    print(f'Number of training nodes: {data.train_mask.sum()}')
    print(f'Training node label rate: {int(data.train_mask.sum()) / data.num_nodes:.2f}')
    print(f'Has isolated nodes: {data.has_isolated_nodes()}')
    print(f'Has self-loops: {data.has_self_loops()}')
    print(f'Is undirected: {data.is_undirected()}')

In [7]:
create_threatrace_edge_list_for_both(config_rec1, own_timestamp_percent=20) # 4min

ALTER TABLE cadets_nodes_01_record ADD subtypes VARCHAR(255) NULL;
Error executing query: 1060 (42S21): Duplicate column name 'subtypes'
ALTER TABLE cadets_nodes_01_record ADD whole_type VARCHAR(255) NULL;
Error executing query: 1060 (42S21): Duplicate column name 'whole_type'
UPDATE cadets_nodes_01_record SET subtypes = CONCAT(subject_type, srcsinkobject_type, fileobject_type, principal_type);
UPDATE cadets_nodes_01_record SET whole_type = CONCAT(node_type, '_', subtypes) WHERE node_type != 'Host' AND node_type != 'Timemarker' AND node_type != 'Endmarker' AND node_type != 'Unitdependency';
CREATE OR REPLACE TABLE tmp1 AS       
                SELECT e.id
                        , e.event_subject_com_bbn_tc_schema_avro_cdm18_uuid as src_uuid
                        , e.event_predicateobject_com_bbn_tc_schema_avro_cdm18_uuid as dst_uuid
                        , e.event_predicateobject2_com_bbn_tc_schema_avro_cdm18_uuid as dst2_uuid
                        , e.event_type
              

In [8]:
# runtime: 4m 50s
create_threatrace_edge_list(config_rec1, False)
create_threatrace_edge_list(config_rec1, True)

rearrange_nodes

                CREATE OR REPLACE TABLE cadets_r01_tt_nodes_train AS
                SELECT DISTINCT src_num AS num, src_uuid AS node, type_s as node_type FROM tmp2_benign
                UNION
                SELECT DISTINCT dst_num AS num, dst_uuid AS node, dst_type as node_type FROM tmp2_benign 
                ORDER BY num;

                ALTER TABLE cadets_r01_tt_nodes_train ADD id INTEGER UNIQUE KEY AUTO_INCREMENT;

                CREATE INDEX IF NOT EXISTS node_id ON cadets_r01_tt_nodes_train (id);
                

                CREATE INDEX IF NOT EXISTS num ON cadets_r01_tt_nodes_train (num);
                
 
                CREATE OR REPLACE TABLE cadets_r01_tt_edges_train AS
                SELECT e.id
                        , src_uuid
                        , src_num
                        , type_s
                        , dst_uuid 
                        , dst_num 
                        , dst_type
                        , event_type
       

In [9]:
# whole runtime 5m 20s
data_test = create_pyg_data_object(config_rec1, True) #runtime 4m # Length = 12082603
data_train = create_pyg_data_object(config_rec1, False) #runtime 4m Length = 12192401

SELECT id FROM cadets_r01_tt_nodes_test;
SELECT DISTINCT event_type FROM cadets_r01_tt_edges_test ORDER BY event_type ASC;
results_query_unique_event_types: [('EVENT_ACCEPT',), ('EVENT_BIND',), ('EVENT_CHANGE_PRINCIPAL',), ('EVENT_CLOSE',), ('EVENT_CONNECT',), ('EVENT_CREATE_OBJECT',), ('EVENT_EXECUTE',), ('EVENT_EXIT',), ('EVENT_FCNTL',), ('EVENT_FLOWS_TO',), ('EVENT_FORK',), ('EVENT_LINK',), ('EVENT_LSEEK',), ('EVENT_MMAP',), ('EVENT_MODIFY_FILE_ATTRIBUTES',), ('EVENT_MODIFY_PROCESS',), ('EVENT_OPEN',), ('EVENT_OTHER',), ('EVENT_READ',), ('EVENT_RECVFROM',), ('EVENT_RECVMSG',), ('EVENT_RENAME',), ('EVENT_SENDMSG',), ('EVENT_SENDTO',), ('EVENT_SIGNAL',), ('EVENT_TRUNCATE',), ('EVENT_UNLINK',), ('EVENT_WRITE',)]
Lenght of results_query_unique_event_types: 28
56
(950774, 57)
SELECT src_num_new, event_type, COUNT(*) FROM cadets_r01_tt_edges_test GROUP BY src_num_new, event_type;
SELECT dst_num_new, event_type, COUNT(*) FROM cadets_r01_tt_edges_test GROUP BY dst_num_new, event_type;
df.sh

/Users/robinbuchta/Documents/GitHub/trustathsh/projekte/secder/Fachliches/darpa_benchmark_lite_sql/benchmark/construct_threatrace_graph.py:396: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_new.cpp:248.)
  


SELECT id FROM cadets_r01_tt_nodes_train;
SELECT DISTINCT event_type FROM cadets_r01_tt_edges_test ORDER BY event_type ASC;
results_query_unique_event_types: [('EVENT_ACCEPT',), ('EVENT_BIND',), ('EVENT_CHANGE_PRINCIPAL',), ('EVENT_CLOSE',), ('EVENT_CONNECT',), ('EVENT_CREATE_OBJECT',), ('EVENT_EXECUTE',), ('EVENT_EXIT',), ('EVENT_FCNTL',), ('EVENT_FLOWS_TO',), ('EVENT_FORK',), ('EVENT_LINK',), ('EVENT_LSEEK',), ('EVENT_MMAP',), ('EVENT_MODIFY_FILE_ATTRIBUTES',), ('EVENT_MODIFY_PROCESS',), ('EVENT_OPEN',), ('EVENT_OTHER',), ('EVENT_READ',), ('EVENT_RECVFROM',), ('EVENT_RECVMSG',), ('EVENT_RENAME',), ('EVENT_SENDMSG',), ('EVENT_SENDTO',), ('EVENT_SIGNAL',), ('EVENT_TRUNCATE',), ('EVENT_UNLINK',), ('EVENT_WRITE',)]
Lenght of results_query_unique_event_types: 28
56
(206693, 57)
SELECT src_num_new, event_type, COUNT(*) FROM cadets_r01_tt_edges_train GROUP BY src_num_new, event_type;
SELECT dst_num_new, event_type, COUNT(*) FROM cadets_r01_tt_edges_train GROUP BY dst_num_new, event_type;
df

In [10]:
print_data_stats(data_train) # Number of nodes: 950774 Number of edges: 12192401 # 10% =  Number of nodes: 127452 Number of edges: 1261612
print_data_stats(data_test) # Number of nodes: 942812 Number of edges: 12082603


Data(x=[206693, 56], edge_index=[2, 2194212], y=[206693], train_mask=[206693], test_mask=[206693])
Number of nodes: 206693
Number of edges: 2194212
Average node degree: 10.62
Number of training nodes: 206693
Training node label rate: 1.00
Has isolated nodes: True
Has self-loops: True
Is undirected: False

Data(x=[950774, 56], edge_index=[2, 12192401], y=[950774], train_mask=[950774], test_mask=[950774])
Number of nodes: 950774
Number of edges: 12192401
Average node degree: 12.82
Number of training nodes: 950774
Training node label rate: 1.00
Has isolated nodes: True
Has self-loops: True
Is undirected: False


In [11]:
print(data_train.y.unique())
print(data_train.x.unique())
print(data_test.y.unique())
print(data_test.x.unique())

tensor([0, 1, 2, 3, 4, 5])
tensor([0.0000e+00, 1.0000e+00, 2.0000e+00, 3.0000e+00, 4.0000e+00, 5.0000e+00,
        6.0000e+00, 7.0000e+00, 8.0000e+00, 9.0000e+00, 1.0000e+01, 1.1000e+01,
        1.2000e+01, 1.3000e+01, 1.4000e+01, 1.5000e+01, 1.6000e+01, 1.7000e+01,
        1.8000e+01, 1.9000e+01, 2.0000e+01, 2.1000e+01, 2.2000e+01, 2.3000e+01,
        2.4000e+01, 2.5000e+01, 2.6000e+01, 2.7000e+01, 2.8000e+01, 2.9000e+01,
        3.0000e+01, 3.1000e+01, 3.2000e+01, 3.3000e+01, 3.4000e+01, 3.5000e+01,
        3.6000e+01, 3.7000e+01, 3.8000e+01, 3.9000e+01, 4.0000e+01, 4.1000e+01,
        4.2000e+01, 4.3000e+01, 4.4000e+01, 4.5000e+01, 4.6000e+01, 4.7000e+01,
        4.8000e+01, 4.9000e+01, 5.0000e+01, 5.1000e+01, 5.2000e+01, 5.3000e+01,
        5.4000e+01, 5.5000e+01, 5.6000e+01, 5.7000e+01, 5.8000e+01, 5.9000e+01,
        6.0000e+01, 6.1000e+01, 6.2000e+01, 6.3000e+01, 6.4000e+01, 6.5000e+01,
        6.6000e+01, 6.7000e+01, 6.8000e+01, 6.9000e+01, 7.0000e+01, 7.1000e+01,
        7.200

In [12]:
# Imports
import os.path as osp
import os
import argparse
import torch
import time
import torch.nn.functional as F
import torch_geometric.transforms as T
import numpy as np
import pandas as  pd
from tqdm import tqdm
from torch_geometric.nn import GCNConv, GAE, VGAE
from torch_geometric.data import Data, InMemoryDataset
from torch_geometric.data import NeighborSampler, DataLoader
from torch_geometric.loader import NeighborLoader
from torch_geometric.nn import SAGEConv, GATConv
from torch_geometric.utils import add_remaining_self_loops
#Reproducibility
from torch_geometric import seed_everything
#from torch.utils.tensorboard import SummaryWriter
#rom tensorboardX import SummaryWriter

In [13]:
seed_everything(1234)

In [14]:
scenario_dir = "/Users/robinbuchta/Documents/DARPA/cadets/01_record/"
models_dir_path = scenario_dir + "models/"
hidden_layer = 32
learning_rate = 0.001
weight_decay = 5e-4
train_shuffle = False
train_num_neighbor = -1
train_hop = 2
train_b_size = 5000
train_thre = 1.5
test_thre = 2
init_epochs = 30
test_cnt_thre = 3 #how many mini-batches are allowed to have 0 true classified nodes
submodel_max_epochs = 150
loop_num = 0

##
test_shuffle = False
test_num_neighbor = -1
test_hop = 2
test_b_size = 5000

In [15]:
models = os.listdir(models_dir_path)
for item in models:
    if item.startswith("model_"):
        os.remove(os.path.join(models_dir_path, item))
    if item.startswith("tn_"):
        os.remove(os.path.join(models_dir_path, item))
    if item.startswith("fp_"):
        os.remove(os.path.join(models_dir_path, item))

In [16]:
class SAGENet(torch.nn.Module):
    def __init__(self, in_channels, out_channels, concat=False):
        super(SAGENet, self).__init__()
        self.conv1 = SAGEConv(in_channels, hidden_layer, normalize=False, concat=concat)
        self.conv2 = SAGEConv(hidden_layer, out_channels, normalize=False, concat=concat)
        #self.lin1 = torch.nn.Linear(256, out_channels)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, p=0.5, training=self.training)
        x = self.conv2(x, edge_index)
        #x = self.lin1(x)
        return F.log_softmax(x, dim=1)

In [17]:
#device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device = torch.device('cpu')
#train_net = SAGENet
train_net = SAGENet 
train_feature_num = data_train.x.shape[1]
train_label_num = len(data_train.y.unique())
train_model = train_net(train_feature_num, train_label_num).to(device)
optimizer = torch.optim.Adam(train_model.parameters(), lr=learning_rate, weight_decay=weight_decay)

In [18]:
train_loader = NeighborLoader(data_train, shuffle=train_shuffle, num_neighbors=[train_num_neighbor] * train_hop, batch_size=train_b_size,input_nodes=data_train.train_mask)

In [19]:

def train():
    train_model.train()
    total_loss = 0
    items = 0
    for data_flow in train_loader:
        data_flow.edge_index = add_remaining_self_loops(data_flow.edge_index)[0]
        optimizer.zero_grad()
        out = train_model(data_flow.x, data_flow.edge_index)
        loss = F.nll_loss(out[:data_flow.batch_size], data_flow.y[:data_flow.batch_size])
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * data_flow.batch_size
        items += data_flow.batch_size
    return total_loss / items



def test(model, loader):
    model.eval()
    correct = 0
    items = 0
    total_loss = 0
    for data_flow in loader:
        data_flow.edge_index = add_remaining_self_loops(data_flow.edge_index)[0]
        out = model(data_flow.x, data_flow.edge_index)
        loss = F.nll_loss(out[:data_flow.batch_size], data_flow.y[:data_flow.batch_size])
        out = out[:data_flow.batch_size]
        pred = out.max(1)[1]
        total_loss += loss.item() * data_flow.batch_size
        correct += pred[:data_flow.batch_size].eq(data_flow.y[:data_flow.batch_size]).sum().item()  
        items += data_flow.batch_size
    return correct / items

In [20]:
def final_test(model, loader, data):
    model.eval()
    correct = 0
    items = 0
    for data_flow in loader:
        data_flow.edge_index = add_remaining_self_loops(data_flow.edge_index)[0]
        out = model(data_flow.x, data_flow.edge_index)
        out = out[:data_flow.batch_size]
        bachted_data_flow_n_id = data_flow.n_id[:data_flow.batch_size]
        pred = out.max(1)[1]
        pro  = F.softmax(out, dim=1)
        pro1 = pro.max(1)
        for i in range(len(bachted_data_flow_n_id)):
            pro[i][pro1[1][i]] = -1
        pro2 = pro.max(1)
        for i in range(len(bachted_data_flow_n_id)):
            if pro1[0][i]/pro2[0][i] < train_thre:
                pred[i] = 100
        for i in range(len(bachted_data_flow_n_id)):
            if data.y[bachted_data_flow_n_id[i]] != pred[i]:
                false_classified.append(int(bachted_data_flow_n_id[i]))
            else:
                true_classified.append(int(bachted_data_flow_n_id[i]))
        correct += pred[:data_flow.batch_size].eq(data_flow.y[:data_flow.batch_size]).sum().item()  
        items += data_flow.batch_size
    return correct / items, false_classified, true_classified

In [21]:
def show(*s):
	for i in range(len(s)):
		print (str(s[i]) + ' ', end = '')
	print (time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(time.time())))

In [22]:
# train first Model on all Data over init_epochs
for epoch in range(1, init_epochs):
    loss = train()
    acc = test(train_model, train_loader)
    #tensorboard
    # writer.add_scalars('acc train', {"acc"+str(loop_num): acc}, epoch) # new line
    # writer.add_scalars('loss train', {"loss"+str(loop_num): loss}, epoch)   # new line

    show(epoch, loss, acc)

1 4.376006634643037 0.8675620364501943 2023-06-07 09:10:01
2 2.600320113155496 0.9466116414198836 2023-06-07 09:10:03
3 2.2705319859162985 0.9450924801517226 2023-06-07 09:10:04
4 1.4832899624376388 0.9526012008147349 2023-06-07 09:10:05
5 0.9279269228269109 0.8850952862457848 2023-06-07 09:10:06
6 1.0153181579030843 0.8884093800951169 2023-06-07 09:10:07
7 0.6592980829985486 0.8845002007808682 2023-06-07 09:10:08
8 0.695781440934025 0.8912638550894322 2023-06-07 09:10:09
9 0.5859581116684304 0.8958406912667579 2023-06-07 09:10:10
10 0.5407138354819481 0.9645367767655412 2023-06-07 09:10:11
11 0.5078437248248838 0.9654753668484177 2023-06-07 09:10:12
12 0.49468090832468453 0.9659301476102239 2023-06-07 09:10:13
13 0.43613094749482195 0.9661285094318627 2023-06-07 09:10:14
14 0.4726565806236278 0.9661865665503911 2023-06-07 09:10:16
15 0.4057821064503578 0.9665736140072475 2023-06-07 09:10:17
16 0.3843107240890972 0.9666897282443043 2023-06-07 09:10:18
17 0.391595002640922 0.96676713773

In [23]:
while (1): # stops if 3 models have 0 true classified, or if acc = 1 
    false_classified = []
    true_classified = []
    acc, false_classified, true_classified = final_test(train_model, train_loader, data_train)
    #tensorboard:
    
    # writer.add_scalar('false_classified train', len(false_classified), loop_num)   # new line
    # writer.add_scalar('true_classified train', len(true_classified), loop_num)   # new line
    if len(true_classified) == 0:
        bad_cnt += 1
    else: 
        bad_cnt = 0
    if bad_cnt >= test_cnt_thre:  # break if 3 times a submodel got 0 true_classified nodes
        break
    print("false_classified, true_classified")
    print(len(false_classified),len(true_classified))
    if len(true_classified) > 0:
        for i in true_classified:
            data_train.train_mask[i] = False
            data_train.test_mask[i] = False
        fw = open(models_dir_path + 'fp_feature_label_'+str(loop_num)+'.txt', 'w')
        x_list = data_train.x[false_classified]
        y_list = data_train.y[false_classified]

        if len(x_list) >1:
            sorted_index = np.argsort(y_list, axis = 0)
            x_list = np.array(x_list)[sorted_index]
            y_list = np.array(y_list)[sorted_index]

        for i in range(len(y_list)):
            fw.write(str(y_list[i])+':')
            for j in x_list[i]:
                fw.write(' '+str(j))
            fw.write('\n')
        fw.close()

        fw = open(models_dir_path + 'tn_feature_label_'+str(loop_num)+'.txt', 'w')
        x_list = data_train.x[true_classified]
        y_list = data_train.y[true_classified]

        if len(x_list) >1:
            sorted_index = np.argsort(y_list, axis = 0)
            x_list = np.array(x_list)[sorted_index]
            y_list = np.array(y_list)[sorted_index]

        for i in range(len(y_list)):
            fw.write(str(y_list[i])+':')
            for j in x_list[i]:
                fw.write(' '+str(j))
            fw.write('\n')
        fw.close()

        torch.save(train_model.state_dict(), models_dir_path + 'model_'+str(loop_num))
        show('Model saved loop_num: ' + str(loop_num))
        # break #use this break for "single model" setup


    train_loader = NeighborLoader(data_train, shuffle=train_shuffle, num_neighbors=[train_num_neighbor] * train_hop, batch_size=train_b_size,input_nodes=data_train.train_mask) #loader neusetzen 

    train_model = train_net(train_feature_num, train_label_num).to(device)
    optimizer = torch.optim.Adam(train_model.parameters(), lr=learning_rate, weight_decay=weight_decay)
    loop_num  += 1
    acc = 0
    for epoch in range(1, submodel_max_epochs):
        loss = train()
        acc = test(train_model, train_loader)
        #tensorboard
        # writer.add_scalars('acc train', {"acc"+str(loop_num): acc}, epoch) # new line
        # writer.add_scalars('loss train', {"loss"+str(loop_num): loss}, epoch)   # new line
        show(epoch, loss, acc)
        if loss < 1: break
    if acc == 1: break 
show('Finish training graph')


false_classified, true_classified
6600 200093
Model saved loop_num: 0 2023-06-07 09:10:40
1 4.3454286979906485 0.04196969696969697 2023-06-07 09:10:40
2 3.7191201051076255 0.049545454545454545 2023-06-07 09:10:40
3 4.293793548237193 0.0543939393939394 2023-06-07 09:10:40
4 4.842928149483421 0.055303030303030305 2023-06-07 09:10:40
5 3.5546381907029585 0.06348484848484849 2023-06-07 09:10:41
6 3.2313028610113896 0.06378787878787878 2023-06-07 09:10:41
7 3.0001371484814268 0.09454545454545454 2023-06-07 09:10:41
8 2.794540766513709 0.09666666666666666 2023-06-07 09:10:41
9 2.543249737132679 0.09833333333333333 2023-06-07 09:10:41
10 3.065993641362046 0.19136363636363637 2023-06-07 09:10:41
11 3.4046119559894907 0.2156060606060606 2023-06-07 09:10:41
12 3.7611606337807397 0.22 2023-06-07 09:10:41
13 2.6636323061856357 0.2221212121212121 2023-06-07 09:10:41
14 2.8517493479179614 0.2721212121212121 2023-06-07 09:10:41
15 3.5130809220400723 0.2759090909090909 2023-06-07 09:10:41
16 2.3914253

In [24]:
#test_net = SAGENet
test_net = SAGENet
test_feature_num = data_test.x.shape[1]
test_label_num = len(data_test.y.unique())
test_model = test_net(test_feature_num, test_label_num).to(device)

In [25]:
test_loader = NeighborLoader(data_test, shuffle=test_shuffle, num_neighbors=[test_num_neighbor] * test_hop, batch_size=test_b_size,input_nodes=data_test.train_mask)

In [26]:
#runime 8min
loop_num = 0
 
while(1):
	if loop_num > 100: break
	model_path = models_dir_path+ 'model_'+str(loop_num)
	if not osp.exists(model_path): 
		loop_num += 1
		continue
	test_model.load_state_dict(torch.load(model_path))
	false_classified = []	
	true_classified = [] 
	test_acc, false_classified, true_classified = final_test(test_model, test_loader, data_test)
	#writer.add_scalar('acc test', acc, loop_num)   # new line
	print("Loop_num: " + str(loop_num) + '  Accuracy:{:.4f}'.format(test_acc) + '  true_classified:' + str(len(true_classified))+ '  false_classified:' + str(len(false_classified)))
	for i in true_classified:
		data_test.test_mask[i] = False
	if test_acc == 1: break
	loop_num += 1
	
    # 51 vs 57 features problems


Loop_num: 0  Accuracy:0.9496  true_classified:902832  false_classified:47942
Loop_num: 1  Accuracy:0.0495  true_classified:47046  false_classified:903728
Loop_num: 2  Accuracy:0.1339  true_classified:127301  false_classified:823473
Loop_num: 3  Accuracy:0.0576  true_classified:54743  false_classified:896031
Loop_num: 4  Accuracy:0.0110  true_classified:10463  false_classified:940311
Loop_num: 5  Accuracy:0.0580  true_classified:55139  false_classified:895635
Loop_num: 6  Accuracy:0.0372  true_classified:35328  false_classified:915446
Loop_num: 7  Accuracy:0.0079  true_classified:7555  false_classified:943219
Loop_num: 8  Accuracy:0.0861  true_classified:81905  false_classified:868869


In [27]:
data_test.test_mask.sum()

tensor(1440)

In [28]:
hits = torch.nonzero(data_test.test_mask).squeeze()

In [29]:
# get Neighbors of atk nodes
atk_nodes = get_atk_nodes(config_rec1)

In [30]:
mapped_atk_nodes = find_mapping_value_for_gt_uuid(config_rec1, atk_nodes)
print(len(mapped_atk_nodes))

SELECT id FROM cadets_r01_tt_nodes_test WHERE node IN ('','53E330C7-39AF-11E8-BF66-D9AA8AFF4A69','52E1C0CA-39B4-11E8-BF66-D9AA8AFF4A69','F974E511-39AD-11E8-BF66-D9AA8AFF4A69','FF6A93D6-39B3-11E8-BF66-D9AA8AFF4A69','FF6824C0-39B3-11E8-BF66-D9AA8AFF4A69','3994EE75-39B0-11E8-BF66-D9AA8AFF4A69','DA98A5A4-79B3-5F89-A952-AC8C11E4653A','53AF6E18-39B3-11E8-BF66-D9AA8AFF4A69','A8C9F4DB-39B3-11E8-BF66-D9AA8AFF4A69','D78A38C5-39B0-11E8-BF66-D9AA8AFF4A69','64926131-39B4-11E8-BF66-D9AA8AFF4A69','94DF461B-39B4-11E8-BF66-D9AA8AFF4A69','5414EF4B-39AF-11E8-BF66-D9AA8AFF4A69','3209A26F-A6EF-0350-AFA6-B1BD1003D390','68D40266-39AF-11E8-BF66-D9AA8AFF4A69','A8F8433D-39B3-11E8-BF66-D9AA8AFF4A69','FF6AB117-39B3-11E8-BF66-D9AA8AFF4A69','BBD8EFE8-D64E-A651-8ED6-037AB1A6F528','EAF868DF-B3BF-5BFD-ACD1-356FEC41B595','323ED9A0-39B1-11E8-BF66-D9AA8AFF4A69','FF6A9431-39B3-11E8-BF66-D9AA8AFF4A69','39787727-39B0-11E8-BF66-D9AA8AFF4A69','65B5CDDA-39B0-11E8-BF66-D9AA8AFF4A69','84F70B35-68E3-FB58-A368-CD5548FBBA24','FF808

In [31]:
mapped_atk_nodes_decremented = [x - 1 for x in mapped_atk_nodes]

In [32]:
print(len(hits))
print(len(mapped_atk_nodes_decremented))

1440
681


In [33]:
from torch_geometric.utils import k_hop_subgraph

mapped_atk_nodes_decremented_with_2_hop, edge_index, mapping, edge_mask = k_hop_subgraph(mapped_atk_nodes_decremented, num_hops=2, edge_index=data_test.edge_index)

In [34]:
print(len(mapped_atk_nodes_decremented_with_2_hop))
print(mapped_atk_nodes_decremented_with_2_hop)

37533
tensor([     0,      4,     14,  ..., 950750, 950755, 950756])


In [35]:
print(hits)
print(mapped_atk_nodes_decremented)
matches = np.intersect1d(hits, mapped_atk_nodes_decremented)
print(len(matches))

tensor([   564,   8173,  20840,  ..., 949233, 949296, 949313])
[950271, 950272, 950273, 950274, 950275, 944132, 948229, 948230, 948231, 944136, 948232, 948233, 948234, 948235, 948236, 948237, 948238, 944144, 948239, 948240, 948241, 20, 948242, 22, 948243, 944152, 948244, 948245, 948246, 28, 29, 944158, 31, 948247, 948248, 948249, 948250, 948251, 948252, 948253, 948254, 948255, 948256, 948257, 944171, 950307, 950308, 950309, 948271, 948272, 950312, 50, 946226, 52, 946228, 54, 55, 946227, 946229, 946230, 946231, 946232, 946233, 946234, 946235, 946236, 946237, 946238, 946239, 946240, 946241, 946242, 946243, 946244, 946245, 946246, 946247, 946248, 946251, 946252, 946253, 946254, 946255, 946256, 946261, 946262, 950387, 950478, 950479, 950480, 950481, 950482, 950483, 950484, 950485, 950486, 950487, 950488, 950489, 950490, 950491, 950492, 950493, 950494, 950495, 950496, 950497, 950498, 950499, 950500, 950511, 950512, 950513, 950514, 950515, 950516, 948485, 948487, 43278, 719128, 170320, 17032

In [36]:
# from torch_geometric.utils import k_hop_subgraph
# # Specify the node for which you want to extract the 2-hop neighborhood
# node_index = list(mapped_atk_nodes)

# # Extract the 2-hop neighborhood
# subset, edge_index, mapping, edge_mask = k_hop_subgraph(node_index, num_hops=2, edge_index=data_test.edge_index)

# # Print the resulting subgraph
# print(subset)
# print(edge_index)
# print(len(subset))
# print(len(edge_index[0]))

In [ ]:
f_gt = open(ground_truth_path, 'r')
f_alarm = open(alarm_path, 'r')
f_tp = open(true_positiv_path, 'w+')
f_fn = open(false_postiv_path, 'w+')
eps = 1e-10

gt = {}
for line in f_gt:
	gt[int(line.strip('\n').split(' ')[0])] = 1
ans = []

In [37]:
from torch_geometric.utils import k_hop_subgraph
 # Specify the node for which you want to extract the 2-hop neighborhood
#runtime: 4m 30s

# f_gt = open(ground_truth_path, 'r')
# f_alarm = open(alarm_path, 'r')
# f_tp = open(true_positiv_path, 'w+')
# f_fn = open(false_postiv_path, 'w+')
eps = 1e-10

hits = hits
gt = mapped_atk_nodes_decremented_with_2_hop
# for line in f_gt:
# 	gt[int(line.strip('\n').split(' ')[0])] = 1
ans = []
flag =0
#for line in f_alarm:
for i in range(len(data_test.x)):
	ans.append('tn')
print("start")
unique_values, counts = np.unique(ans, return_counts=True)
print(dict(zip(unique_values, counts)))
for i in gt:
	ans[i] = 'fn'
print("gt")
unique_values, counts = np.unique(ans, return_counts=True)
print(dict(zip(unique_values, counts)))
for i in hits:
	i_as_list = [i]
	hit_neighbors, edge_index, mapping, edge_mask = k_hop_subgraph(i_as_list, num_hops=2, edge_index=data_test.edge_index)
	for neighbor in hit_neighbors.tolist():
		if neighbor in gt:
			ans[neighbor] = 'tp'
			flag = 1
	if i in gt:
		ans[i] = 'tp'
		flag = 1
	else:
		if flag == 0:
			ans[i] = 'fp'
unique_values, counts = np.unique(ans, return_counts=True)
print(dict(zip(unique_values, counts)))


tn = 0
tp = 0
fn = 0
fp = 0
count = 0
for i in ans:
	if i == 'tp': tp += 1
	if i == 'tn': tn += 1
	if i == 'fp': 
		fp += 1
	if i == 'fn': 
		fn += 1
		#f_fn.write(str(count) + "\n")
	count = count +1
print(count)
print(tp,fp,tn,fn)
print("TP: {tp}, FP: {fp}, TN: {tn}, FN: {fn}".format(tp = tp, fp = fp, tn = tn, fn = fn))
precision = tp/(tp+fp+eps)
recall = tp/(tp+fn+eps)
fscore = 2*precision*recall/(precision+recall+eps)
# writer.add_scalar('Precision', precision, 0)   # new line
# writer.add_scalar('Recall', recall,0)   # new line
# writer.add_scalar('F-Score', fscore,0)   # new line
accuracy = (tp + tn) / (tp + tn + fp + fn)
print('Precision: ', precision)
print('Recall: ', recall)
print('F-Score: ', fscore)
print("Accuracy: ", accuracy)

# geschönt und fertig :D 

start
{'tn': 950774}
gt
{'fn': 37533, 'tn': 913241}
{'fn': 34560, 'tn': 913241, 'tp': 2973}
950774
2973 0 913241 34560
TP: 2973, FP: 0, TN: 913241, FN: 34560
Precision:  0.9999999999999664
Recall:  0.07921029494045219
F-Score:  0.1467930676800724
Accuracy:  0.9636506677717313


In [104]:
type(ans)

list

In [105]:
import numpy as np

# Create a list
my_list = ['tp', 'tp', 'fp', 'tp', 'fn']

# Convert the list to a NumPy array
my_array = np.array(ans)

# Find the indices where the condition is met (e.g., values equal to 'tp')
indices = np.where(my_array == 'tp')[0]

print(indices)

[     0      4     41 ... 950277 950481 950487]


In [106]:
len(hits)

129

In [107]:
htis

NameError: name 'htis' is not defined

In [ ]:
hits

tensor([    41,  40486,  41343,  65549,  90417, 170360, 174424, 174533, 174580,
        189310, 225766, 226764, 244001, 491112, 620619, 669347, 669461, 670570,
        670998, 671439, 672538, 673284, 673756, 674600, 675944, 676532, 676869,
        677674, 678850, 679027, 679282, 679510, 679987, 680501, 681422, 682217,
        683517, 684544, 685160, 686442, 686800, 687443, 688074, 688576, 688626,
        690456, 690965, 691899, 693086, 694431, 694493, 694872, 695202, 695296,
        695533, 695806, 696108, 696213, 696483, 697536, 697599, 698216, 698402,
        698963, 699069, 699278, 700365, 701233, 702595, 703496, 704799, 706711,
        707880, 709231, 710203, 712199, 712530, 713521, 714056, 714169, 714832,
        715034, 715878, 717929, 719250, 719691, 720160, 721849, 722655, 723461,
        724513, 725309, 726308, 726960, 727461, 728705, 729959, 731024, 733029,
        733531, 735377, 736194, 737832, 740063, 740988, 741535, 742003, 742402,
        743698, 744004, 744092, 744483, 

In [109]:
data_test.y[hits]

tensor([3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        4, 4, 3, 5, 5, 5, 5, 4, 4])